config/routes.rb
Rails.application.routes.draw do
root 'people#index'
resources :people

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to people_path
    else render :edit
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to people_path
  end

  private

  def person_params
    params.require(:person).permit(:name, :age, :hair_color, :eye_color, :gender, :alive)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyRailsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h2>Edit</h2>
<hr />

<%= form_for @person do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.label :age %>
  <%= f.text_field :age %>
  <br />

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>
  <br />

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>
  <br />

  <%= f.label :gender %>
  <%= f.text_field :gender %>
  <br />

  <%= f.label :alive %>
  <%= f.text_field :alive %>
  <br />

  <%= f.submit %>
<% end %>

app/views/people/index.html.erb
<h2> People </h2>
  <hr />
  <% if @people.empty? %>
    <h3>No people found, please create someone!</h3>
  <% else %>
    <% @people.each do |person| %>
    <h3><%= person.name %></h3>
    <!-- <h4><%= person.age %></h4>
    <h4><%= person.hair_color %></h4>
    <h4><%= person.eye_color %></h4>
    <h4><%= person.gender %></h4>
    <h4><%= person.alive %></h4> -->
    <%= link_to 'Show person', person_path(person) %>
    <%= link_to 'Destroy person', person, method: :delete %>
    <% end %>
  <% end %>
  <%= link_to 'New', new_person_path %>

app/views/people/new.html.erb
<h2>New</h2>
<hr />

<%= form_for @person do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.label :age %>
  <%= f.text_field :age %>
  <br />

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>
  <br />

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>
  <br />

  <%= f.label :gender %>
  <%= f.text_field :gender %>
  <br />

  <%= f.label :alive %>
  <%= f.text_field :alive %>
  <br />

  <%= f.submit %>
<% end %>

app/views/people/show.html.erb
<h2> Person </h2>
  <hr />
  <h3><%= @person.name %></h3>
  <h4><%= @person.age %></h4>
  <h4><%= @person.hair_color %></h4>
  <h4><%= @person.eye_color %></h4>
  <h4><%= @person.gender %></h4>
  <h4><%= @person.alive %></h4>
  <%= link_to 'Edit', edit_person_path(@person) %>
  <%= link_to 'Destroy person', @person, method: :delete %>
  <%= link_to 'Back', people_path %>